# Model arguments
model_name_or_path: outputs/Target-SFT
torch_dtype: null
attn_implementation: flash_attention_2


# Data training arguments
dataset_mixer:  your_datapath_for_wrpo
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 0.01
alpha: 0.1
is_dynamic: true # set to false if you want static alpha
do_eval: true
evaluation_strategy: steps
eval_steps: 500
loss_type: wrpo
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: wrpo-models
learning_rate: 3.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/Target-SFT-WRPO
run_name: Target-SFT-WRPO
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "no"
save_steps: 5000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
save_only_model: true